#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d     

bspc config border_width         2
bspc config window_gap           2

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true
bspc config active_border_color \#e6e1cf

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

#nitrogen --restore &
feh --
/usr/lib/xfce4/notifyd/xfce4-notifyd &
xfce4-power-manager &
lxpolkit &
nm-applet &
volumeicon &
picom &
blueman-applet &
/home/$(whoami)/.config/polybar/launch.sh &
